Update README.md
coreruleset/plugin-registry pull request #17
Opened 2024-02-11 02:31 UTC by eilandert

Adding wordpress-hardening-plugin.

Although I run this on a couple of boxes now, I do have to review everything once more. 
Input is much appreciated, since I have just started with modsecurity ;-)

2024-02-11 07:28 UTC, theseion requested changes

2024-02-11 07:28 UTC, theseion commented on README.md
> +| wordpress-hardening-plugin          | 9,522,000 - 9,522,999 | https://github.com/eilandert/wordpress-hardening-plugin                  | 3rd party | being tested        |      |
```suggestion
| wordpress-hardening-plugin          | 9,522,000 - 9,522,999 | https://github.com/eilandert/wordpress-hardening-plugin                  | 3rd party | untested        |      |
```

2024-02-11 07:32 UTC, theseion commented
Thank you @eilandert. What is your rational for this plugin? Does it include additional blocking rules (as opposed to rule exclusions)? Should it be installed alongside the `wordpress-rule-exclusions` plugin? The answers to these questions should also be documented in the README of your plugin.

2024-02-11 13:58 UTC, dune73 commented
Thank you very much. This is very welcome.

We are currently in the final stages of the CRS v4 release. Reviewing and sharing some advice, will probably take a few days and we're very busy. But I really like the initiative.

2024-02-12 17:00 UTC, eilandert commented
> Thank you @eilandert. What is your rational for this plugin? Does it include additional blocking rules (as opposed to rule exclusions)? Should it be installed alongside the `wordpress-rule-exclusions` plugin? The answers to these questions should also be documented in the README of your plugin.

The goal is to harden Wordpress a bit more without interfering with it's operation, hopefully our users can drop their security-plugins in Wordpress in the future. It will only contain extra blocking rules since there is already an exclusion-plugin.  Both can be used, in fact it's encouraged to use the exclusions-plugin.  

I have updated the README but will do it in more details soon.

2024-02-12 17:01 UTC, eilandert commented
> Thank you very much. This is very welcome.
> 
> We are currently in the final stages of the CRS v4 release. Reviewing and sharing some advice, will probably take a few days and we're very busy. But I really like the initiative.

That's ok, I've got time ;-)

2024-02-12 18:14 UTC, theseion approved these changes

2024-02-12 18:14 UTC, theseion commented
Sounds great, thanks!

2024-02-12 18:15 UTC, merged